= Usine Logicielle

:toc:

L'objectif de l'Usine Logicielle est de nous permettre de réaliser nos développements en mode Continuous Delivery : tout commit sur un dépôt GIT d'une application déclenche La construction des binaires de l'application suivi du déploiement de l'application.

Pour ce faire, l'Usine Logicielle fournit des outils pour automatiser la construction des binaires ainsi que des environnements de déploiement.

== Outillage

L'Outillage mis en place permet :

* La gestion des sources des Applications.
* La construction des binaires de l'application et l'exécution des tests unitaires (via Jenkins)
* L'archivage des binaires (dans Nexus)
* L'analyse qualité des sources (via SonarQube)

=== Gestion des Sources

L'architecture applicative que nous construisons est une architecture orientée micro services.

Les sources sont hébergées dans une Organisation Github https://github.com/SofteamOuest-Opus[dédiée].

Les sources d'un service sont gérées dans un dépôt GIT.

=== Jenkins

==== Job de BUILD

Le Job de BUILD d'une application permet de :

* Construire l'image Docker de l'application (en version SNAPSHOT)
* Déclencher un Job de Déploiement

En fin de BUILD, sur la branche develop, l'application est déployée sur le cluster, dans un environnement DEV.

==== Job de RELEASE

Le Job de RELEASE d'une application permet de :

* Construire l'image Docker de l'application en version RELEASE
* Construire les jars de l'application en version RELEASE
* Déployer les jars de l'application sur le nexus

Le job de RELEASE d'un Chart prend en paramètre :

* La version de la RELEASE
* La prochaine version de développement

==== Job de RELEASE d'un Chart

Un Chart Helm est un package de déploiement d'une application dans Kubernetes.

Le dépôt Charts centralise :

* Les packages Helm (appelés Charts) de toutes les applications.
* Les RELEASES des charts : une RELEASE d'un chart est une archive TGZ.

Le job de RELEASE d'un Chart prend en paramètre la version de la RELEASE et génère l'archive TGZ.

==== Job de RUN

Le Job de RUN permet de déployer une application sur le cluster.

C'est un Job paramétrable qui prend en paramètre :

* Le nom de l'application à déployer
* Le tag de l'image Docker à déployer
* La version du package Helm à utiliser pour le déploiement
* L'environnement de déploiement (dev, prod)

==== Job de FULL-RUN

Le Job de FULL-RUN permet de déployer toutes les Applications.

Il prend les même paramètres que le Job de RUN (pour chaque application à déployer).

Si le tag de l'image Docker d'une application n'est pas défini, l'application n'est pas déployée.

=== Nexus

Nous utilisons [Nexus](https://nexus.k8.wildwidewest.xyz/) pour archiver les images Docker.

Les accès au serveur Nexus sont authentifiés par login, password.

=== SonarQube

Nous utilisons [SonarQube](https://sonarqube.k8.wildwidewest.xyz/) pour analyser la qualité du code développé.

Les accès au serveur SonarQube sont authentifiés par token.

=== JIRA

== Environnements

=== DEV, RE7, PROD

L'environnement de DEV permet de tester la dernière version SNAPSHOT des Applications.

L'environnement de RE7 permet de tester une version RELEASE avant Mise en Prod.

L'environnement de PROD correspond à l'environnement utilisé.

=== Kubernetes

=== Applications

Nous utilisons le packaging [Helm](https://www.helm.sh/) pour déployer nos applications dans notre cluster [Kubernetes](https://kubernetes.io/).

=== Dépôt Charts

=== Persistance des Données

=== Centralisation des Logs

=== Monitoring

=== Tolérance aux Pannes

==== Panne des Applications

Mise en Place du HealthCheck

==== Panne du Cluster

Mise en Place du HealthCheck