= Usine Logicielle

:toc:

== Outillage

L'Usine Logicielle comporte l'outillage nécessaire à

* L'exécution des Tests Unitaires (mvn, gradle, ...)
* La construction des binaires (Jenkins)
* L'archivage des binaires (Nexus)
* L'analyse qualité des sources (SonarQube)

=== Gestion des Sources

L'architecture applicative que nous construisons est une architecture orientée micro services.

Les sources sont hébergées dans une Organoisation Github [dédiée](https://github.com/SofteamOuest-Opus).

Les sources d'un service sont gérées dans un dépôt GIT.

=== Jenkins

==== Jobs de BUILD

Le Job de BUILD d'une Application permet de :

* Construire l'image Docker de l'Application (en version SNAPSHOT)
* Déclencher un Job de Déploiement

En fin de BUILD, sur la branche develop, l'Application est déployée sur le cluster, dans un environnement DEV.

==== Jobs de RELEASE

Le Job de RELEASE d'une Application permet de :

* Construire l'image Docker de l'Application en version RELEASE
* Déployer les jars de l'Application sur le nexus

==== Jobs de RELEASE d'un Chart

Un Chart Helm est un package de déploiement d'une Application dans Kubernetes.

Le dépôt Charts centralise :

* Les packages Helm (appelés Charts) de toutes les applications.
* Les RELEASES des charts : une RELEASE d'un chart est une archive TGZ.

Le job de RELEASE d'un Chart prend en paramètre la version de la RELEASE et génère l'archive TGZ.

==== Job de RUN

Le Job de RUN permet de déployer une Application sur le cluster.

C'est un Job paramétrable qui prend en paramètre :

* Le nom de l'Application à déployer
* Le tag de l'image Docker à déployer
* La version du package Helm à utiliser pour le déploiement

==== Job de FULL-RUN

Le Job de FULL-RUN permet de déployer toutes les Applications.

Il prend les même paramètres que le Job de RUN (pour chaque Application à déployer).

Si le tag de l'image Docker d'une Application n'est pas défini, l'Application n'est pas déployée.

=== Nexus

Nous utilisons [Nexus](https://nexus.k8.wildwidewest.xyz/) pour archiver les images Docker.

Les accès au serveur Nexus sont authentifiés par login, password.

=== SonarQube

Nous utilisons [SonarQube](https://sonarqube.k8.wildwidewest.xyz/) pour analyser la qualité du code développé.

Les accès au serveur SonarQube sont authentifiés par token.

== Environnements

=== DEV, REC, PROD

=== Applications

Nous utilisons le packaging [Helm](https://www.helm.sh/) pour déployer nos applications dans notre cluster [Kubernetes](https://kubernetes.io/).

=== Dépôt Charts



=== Persistance des Données

=== Centralisation des Logs

=== Monitoring

=== Tolérance aux Pannes

==== Panne des Applications

Mise en Place du HealthCheck

==== Panne du Cluster

Mise en Place du HealthCheck