=  Functional Specification - Team Skill Management Application

:toc:

== Scenarios

=== Scenario TEAMSKILL_1: Browse teams
....
Given I am logged as a XXXX
When I access to team selection screen
Then I can see the teams present in the system with the following information
* the team name
* the agency to which the team belongs
* the number of requirements set
....

=== Scenario TEAMSKILL_2: Display skill requirements
....
Given I am logged as a XXXX on the selection screen
When I select a team
Then I can see team's composition and their skill level for each skill requirement set on the team
....
==== Business rules
* <<BR SKILL_1>>
* <<BR SKILL_2>>
* <<BR SKILL_3>>
* <<BR SKILL_4>>

=== Scenario TEAMSKILL_3: Edit Team
....
Given I am logged as a XXXX on the team details screen
When I pick a new skill
And set a corresponding level
Then I can add that minimum skill requirement to the team
....
==== Business rules
* <<BR SKILL_1>>
* <<BR SKILL_2>>
* <<BR SKILL_3>>

=== Scenario TEAMSKILL_4: Display skill radar
....
Given I am logged as a XXXX on the selection screen
When I select a team
Then I can see the minimum team skill requirements in a radar, filled with the maximum skill level reached by the team members
....
==== Business rules
* <<BR SKILL_1>>
* <<BR SKILL_2>>
* <<BR SKILL_3>>
* <<BR SKILL_4>>

=== Scenario EVENT_LISTEN_1: Team creation
....
Given Team Skill management running
When a team creation event is broadcasted
Then the team must be saved in the system
And the team must be accessible through the team selection screen
....
==== Business rules
* <<BR TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_2>>

=== Scenario EVENT_LISTEN_2: Team update
....
Given Team Skill management running
When a team update event is broadcasted
Then the team name and it's members must be updated
....
==== Business rules
* <<BR TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_2>>

=== Scenario EVENT_LISTEN_3: Team delete
....
Given Team Skill management running
When a team delete event is broadcasted
Then the team must no longer be visible on the team selection screen
....
==== Business rules
* <<BR TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_1>>
* <<BR EVENT_TEAMSKILL_2>>

=== Scenario EVENT_LISTEN_4: User creation
....
Given Team Skill management running
When a user-creation event is broadcasted
Then the user last name and first name must be visible on the team edition screen
....
==== Business rules
* <<BR USER_1>>
* <<BR USER_2>>

=== Scenario EVENT_LISTEN_5: User update
....
Given Team Skill management running
When a user-update event is broadcasted
Then the user last name and first name must be updated on the team edition screen
....
==== Business rules
* <<BR USER_1>>
* <<BR USER_2>>

=== Scenario EVENT_LISTEN_6: User delete
....
Given Team Skill management running
When a user-delete event is broadcasted
Then the user be deleted from the team to which it belongs
....

=== Scenario EVENT_LISTEN_7: User skill update
....
Given Team Skill management running
When a user-skill-update event is broadcasted
Then the user skill levels must be updated on the team edition screen
....
==== Business rules
* <<BR EVENT_USER_SKILL_1>>
* <<BR EVENT_USER_SKILL_2>>
* <<BR SKILL_1>>

=== Scenario EVENT_PUBLISH_1: Team requirement updated
....
Given I am logged as a XXXX on the selection screen
When the minimum skill requirements of a team is edited
Then an update event must be broadcasted
....

== Business rule list

=== BR SKILL_1
....
Skill levels are integers between 1 and 5 inclusive
....
=== BR SKILL_2
....
Skills attach to a team always have a level
....
=== BR SKILL_3
....
A skill can only appear once in a team
....
=== BR SKILL_4
....
If a user skill is higher that the maximum defined in  <<BR SKILL_1>>, the value must be truncated to the maximum
....
=== BR TEAMSKILL_1
....
A team name size must be between 1 and 32 characters
....
=== BR EVENT_TEAMSKILL_1
....
If a member of the group isn't known by the system yet, the member must be added with all the provided fields
....
=== BR EVENT_TEAMSKILL_2
....
If a member of the group has been deleted, the member must be ignored from the team
....
=== BR EVENT_USER_SKILL_1
....
If the user isn't known by the system yet, the user must be created with all the provided fields
....
=== BR EVENT_USER_SKILL_2
....
If the user has been deleted, the event must be ignored
....
=== BR USER_1
....
A user first name size must be between 1 and 32 characters
....
=== BR USER_2
....
A user last name size must be between 1 and 32 characters
....
