== Manage projects features

=== Scenario PRJ_1 : List project

....
Given User is connected as 'project manager'
When User asks projects list
Then entire projects list is displayed
....

=== Scenario PRJ_2 : Add project

....
Given User is connected as 'project manager'
When User create a new project
And User specify a name and a customer
And User asks projects list
Then project is visible in projects list
....

=== Scenario PRJ_3 : Modify project

....
Given User is connected as 'project manager'
When User change name of one project
And User asks projects list
Then project name is changed
....

=== Scenario PRJ_4 : Delete project

....
Given User is connected as 'project manager'
When User delete one project
And User asks projects list
Then project no longer exists
....

==== Business Rules List

<<RG_PRJ_1_1>>, <<RG_PRJ_1_2>>,<<RG_PRJ_2>>, <<RG_PRJ_3>>

===== RG_PRJ_1

Data of a project are :

* Id : unique, readable
* Name : unique, readable/writable
* Description : readable/writable
* Customer : readable/writable

===== RG_PRJ_2

Customer associated to a project comes from customer repository


===== RG_PRJ_3

Data diplayed in projects list are :

* Name : unique, readable/writable
* Customer : readable/writable

===== RG_PRJ_4

Role allowed to add/modify/delete/request project is 'Project manager'