== Manage projects features

=== Scenario PRJ_1 : List Project

....
Given User is connected as Project manager
And projects exist
When User asks projects list
Then entire projects list is displayed
....
<<RG_PRJ_2>>,<<RG_PRJ_3>>

=== Scenario PRJ_2 : Add Project

....
Given User is connected as Project manager
When User creates a new Project
And User specifies a name and a Tenant
And User asks projects list
Then Project is visible in projects list
....
<<RG_PRJ_1>>,<<RG_PRJ_3>>

=== Scenario PRJ_3 : Modify Project

....
Given User is connected as Project manager
And User select a Project
When User changes Project name
And User changes Project Tenant
And User asks projects list
Then Project name and Tenant are changed
....
<<RG_PRJ_1>>,<<RG_PRJ_3>>

=== Scenario PRJ_4 : Delete Project

....
Given User is connected as Project manager
When User delete one project
And User asks projects list
Then project no longer exists
....
<<RG_PRJ_3>>

==== Business Rules List

<<RG_PRJ_1>>,<<RG_PRJ_2>>,<<RG_PRJ_3>>

===== RG_PRJ_1

Data of a project are :

* Id : unique, readable
* Name : unique, readable/writable
* Description : readable/writable
* Tenant : string

All fields are mandatory


===== RG_PRJ_2

Data displayed in projects list are :

* Name : unique, readable/writable
* Tenant : readable/writable

===== RG_PRJ_3

Role allowed to add/modify/delete/request project is Project manager