= Software Requirements Specification - User Mgmt Application

:toc:

== List of User Scenarios

=== Scenario U_1

....
Given an Employee
When I am logged in as this Employee 
Then I can view my profile and personal data
....

So that::
I can read and control my personal informations

==== Business Rules

<<RG U_1_1>>

=== Scenario U_2

....
Given an Employee
When I am logged in as this Employee 
Then I can edit my personal data
....

So that::
my profile is up to date

==== Business Rules

<<RG U_2_1>>

<<RG U_2_2>>

=== Scenario U_3

....
Given a Human resource manager
And an Employee
When I am logged in as this Human resource manager 
Then I can view that Employee's personal data
....

So that::
I can read and control her/his personal informations

==== Business Rules

<<RG U_1_1>> 

<<RG U_3_1>>

=== Scenario U_4

....
Given a Human resource manager
And an Employee
When I am logged in as this Human resource manager 
Then I can edit that Employee's personal data
....

So that::
sensitive information on his profile are up to date

==== Business Rules

<<RG U_2_1>> 

<<RG U_2_2>> 

<<RG U_4_1>>

=== Scenario U_5

....
Given a Human resource manager
When I am logged in as this Human resource manager 
Then I can create a new Employee
....

So that::
newly hired employees or missing employees are visible in the application

==== Business Rules

<<RG U_2_1>>

<<RG U_2_2>>

<<RG U_4_1>>

=== Scenario U_6

....
Given a Human resource manager
And an Employee (former or actual)
When I am logged in as this Human resource manager 
Then I can delete personal data of this Employee 
....

So that::
his profile can be made anonymous and the application is GDPR conformant

==== Business Rules

<<RG U_6_1>>

== Business Rules

=== RG U_1_1

Personal data _readable_ by Employee are :

* Last Name
* First Name
* E-mail address
* Photo
* Office (Nantes/Rennes)
* Date of hire
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Occupation
* Access rights (Employee/Human resource manager/Top management)

Used in: <<Scenario U_1>>, <<Scenario U_3>>

=== RG U_2_1

Personal data _editable_ by Employee on _his own profile_ are :

* Last Name
* First Name
* E-mail address
* Photo

Used in: <<Scenario U_2>>, <<Scenario U_4>>, <<Scenario U_5>>

=== RG U_2_2

Mandatory fields in personal data ::
* Last Name
* First Name
* E-mail address

Used in: <<Scenario U_2>>, <<Scenario U_4>>, <<Scenario U_4>>

=== RG U_3_1

Personal data _readable_ by Human resource manager on _any profile_ are :

* Last Name
* First Name
* E-mail address
* Photo URL
* Office (Nantes/Rennes)
* Date of hire
* Leaving date
* Leaving cause
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Occupation
* Access rights (Employee/Human resource manager/Top management)

<<Scenario U_3>>

=== RG U_4_1

Personal data _editable_ by Human resource manager on _any profile_ are :

* Last Name
* First Name
* E-mail address
* Photo URL
* Office (Nantes/Rennes)
* Date of hire
* Leaving date
* Leaving cause
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Occupation
* Access rights (Employee/Human resource manager/Top management)

Used in: <<Scenario U_4>>, <<Scenario U_5>>

=== RG U_6_1

Personal data to anonymize are :

* Last Name
* First Name
* E-mail address
* Photo URL
* Day/Month of Date of Hire

<<Scenario U_6>>

== Annexes

=== Roles
Roles as used in _user stories_.

* Employee
* Human resource manager
* Top management
* System
* External application

=== Occupation 
* Employee
* Manager
* Human resource manager
* Top management

Was previously labeled _Function_.

=== Status
* Internship
* Subcontractor
* Freelancer

=== Access rights
* Employee
* Human resource manager
* Top management
