= Software Design Description - User Mgmt Application

:toc:

== Technical Scenarios

=== Scenario S_1

....
Given an Employee with valid credentials
When I login as this Employee
Then I can access the application according to my access rights
....

=== Scenario S_2

....
Given an Administrator with an Employee list
When I bulk insert this list
Then all employees are created or updated
....

So that::
database can be seeded faster

==== Business Rules

<<RG S_2_1>>

=== Scenario S_3

....
Given an Employee
And an authenticated external application
When that external application requests for personal data of this Employee
Then it can read personal data of this Employee
....

So that::
it can update his own database

==== List of Business Rules

<<RG S_3_1>>

<<RG S_3_2>>

=== Scenario S_4

....
Given an Employee
And an authenticated external application
When this employee is updated
Then that external application is notified of the update
....

So that::
The external application can perform any relevant operation of its own

==== List of Business Rules

<<RG S_4_1>>

<<RG S_4_2>>

See also: <<Published events>>

== Business Rules

=== RG S_2_1

Bulk inserted personal data are  :

* Last Name
* First Name
* E-mail address
* Office (Nantes/Rennes)
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Function
* Access rights (Employee/Human resource manager/Top management)

Used in: <<Scenario S_2>>

=== RG S_3_1

Personal data _readable_ by external application are :

* Technical identifier
* Last Name
* First Name
* E-mail address
* Photo URL
* Office (Nantes/Rennes)
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Function
* Access rights (Employee/Human resource manager/Top management)

Used in: <<Scenario S_3>>

=== RG S_3_2

The external application can request information for an employee by searching with :

* Technical identifier
* Last Name
* First Name
* E-mail address

Used in: <<Scenario S_3>>

=== RG S_4_1

External application is notified when :
* Employee is created
* Employee is deleted
* Employee is modified

Used in: <<Scenario S_4>>

=== RG S_4_2

Notifications to External application should have :
* Technical identifier
* Last Name
* First Name
* E-mail address
* Photo URL
* Office (Nantes/Rennes)
* Manager
* Human resource manager
* Status (Internship/Subcontractor/Freelancer)
* Function
* Access rights (Employee/Human resource manager/Top management)

See also: <<Published events>>

Used in: <<Scenario S_4>>

== Source code

Source code of front and back-end applications are available in git.

https://github.com/SofteamOuest-Opus/user-mgmt

== Data Design

=== REST API

A RESTful API is available to read informations about Employees.

Documentation on methods/arguments of this API is available in OpenAPI format:

https://github.com/SofteamOuest-Opus/user-mgmt/blob/master/api/public/doc/openapi.yaml

== Architecture Design

=== Events

==== Published events

Events are published into a message queue whenever an Employee is created, deleted or modified.

Events are published in the _employee_ topic.

Documentation on events and messages published in this topic is available in Avro format:

https://github.com/SofteamOuest-Opus/user-mgmt/blob/master/api/public/doc/employees.avsc

== Interface Design

Employee mockups::
link:./wireframes/employee/html/index.html[HTML]

HR Manager mockups::
link:./wireframes/hr-manager/html/index.html[HTML]

== Annexes

Open API Specification::
https://swagger.io/docs/specification/about/

Avro Schema Specification::
http://avro.apache.org/docs/current/spec.html
