=  Spec Fonctionnelle - Application User Mgmt

:toc:

== Liste des scénarios utilisateur

=== Scénario U_1

....
En tant que Collaborateur
Je veux me connecter
Afin de pouvoir utiliser l'application en fonction des droits qui me sont autorisés
....

=== Scénario U_2

....
En tant que Collaborateur
Je veux pouvoir consulter mon profil
Afin de vérifier les informations me concernant
....

==== Liste des RG

===== RG U_2_1

Les informations personnelles pouvant être _consultées_ par le collaborateur sont :

* Nom
* Prénom
* Photo
* Agence de rattachement (Nantes/Rennes)
* Date entrée dans l’entreprise
* Nom du manager
* Nom du RH
* Statut (Stagiaire/Sous traitant/Indépendant)
* Droits (Collaborateur/Resources Humaines/Direction)

=== Scénario U_3

....
En tant que Collaborateur
Je veux pouvoir modifier mes informations personnelles
Afin de mettre à jour mon profil
....

==== Liste des RG

===== RG U_3_1

Les informations personnelles pouvant être _modifiées_ par le collaborateur sur _son propre profil_ sont :

* Nom
* Prénom
* Adresse e-mail
* URL Photo

=== Scénario U_4

....
En tant que Resources humaines
Je veux pouvoir consulter les informations personnelles d'un autre collaborateur
Afin de vérifier les informations le concernant
....

==== Liste des RG

cf. <<RG U_2_1>> 

===== RG U_4_1

Les informations personnelles pouvant être _consultées_ par les Resources humaines sur _l'ensemble des profils_ sont :

* Nom
* Prénom
* Adresse e-mail
* URL Photo
* Agence de rattachement (Nantes/Rennes)
* Date entrée dans l’entreprise
* Date de sortie
* Cause de sortie
* Nom du manager
* Nom du RH
* Statut (Stagiaire/Sous traitant/Indépendant)
* Droits (Collaborateur/Resources Humaines/Direction)

=== Scénario U_5

....
En tant que Resources humaines
Je veux pouvoir modifier les informations personnelles d'un autre collaborateur
Afin de mettre à jour les données sensibles de son profil
....

==== Liste des RG

cf. <<RG U_3_1>> 

===== RG U_5_1

Les informations personnelles pouvant être _modifiées_ par les Resources humaines sur _l'ensemble des profils_ sont :

* Nom
* Prénom
* Adresse e-mail
* URL Photo
* Agence de rattachement (Nantes/Rennes)
* Date entrée dans l’entreprise
* Date de sortie
* Cause de sortie
* Nom du manager
* Nom du RH
* Statut (Stagiaire/Sous traitant/Indépendant)
* Droits (Collaborateur/Resources Humaines/Direction)

=== Scénario U_6

....
En tant que Resources humaines
Je veux pouvoir créer un nouveau collaborateur
Afin de mettre à jour les données sensibles de son profil
....

==== Liste des RG

cf. <<RG U_3_1>>, <<RG U_5_1>>


=== Scénario U_7

....
En tant que Resources humaines
Je veux pouvoir supprimer les données personnelles d'un collaborateur (ancien ou actuel)
Afin d'anonymiser son profil et de me conformer au RGPD
....

===== RG U_7_1

Les informations personnelles à anonymiser sont :

* Nom
* Prénom
* Adresse e-mail
* URL Photo
* jour/mois de la date d'entrée dans l’entreprise
* jour/mois de la date de sortie

== Liste des scénarios système

=== Scénario S_1

....
En tant que Système
Je veux pouvoir charger en masse une liste de collaborateurs
Afin d'initialiser la base de données plus rapidement
....

==== Liste des RG

===== RG S_1_1

Les informations personnelles pouvant être chargées en masse sont :

* Nom
* Prénom
* Adresse e-mail
* Agence de rattachement (Nantes/Rennes)
* Nom du manager
* Nom du RH
* Statut (Stagiaire/Sous traitant/Indépendant)
* Droits (Collaborateur/Resources Humaines/Direction)

=== Scénario S_2

....
En tant que Application externe
Je veux pouvoir consulter les informations personnelles d'un collaborateur
Afin de mettre à jour ma base de données
....

==== Liste des RG

===== RG S_2_1

Les informations personnelles pouvant être _consultées_ par l'application externe sont :

* Nom
* Prénom
* Adresse e-mail
* URL Photo
* Agence de rattachement (Nantes/Rennes)
* Nom du manager
* Nom du RH
* Statut (Stagiaire/Sous traitant/Indépendant)
* Droits (Collaborateur/Resources Humaines/Direction)

=== Scénario S_3

....
En tant que Application externe
Je veux pouvoir être notifié lors de la mise à jour des données d'un collaborateur
Afin de réaliser les opérations nécessaires
....

== Annexes

=== Rôles

* Collaborateur
* Resources humaines
* Direction
* Système
* Application externe

